### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
So that the whole `main.ts` file is covered in the README and no copy/paste errors emerge

### CODE REVIEW

**Comment by hotforfeature** [comment]
I'm not sure I see the value in adding this. The code samples in the readme and docs should be slim and referring to just what the example is talking about.

More specifically, the `enableLegacyTemplate` option [is broken](https://github.com/angular/angular/issues/15555) and [won't do anything](https://github.com/angular/angular/issues/15557) at the moment. Setting production mode from the environment is also specific to Angular CLI projects only.

The only change I see that needs to be present is the AppModule import, which was missing.

**Comment by BorntraegerMarc** [comment]
Well, depends on what you want to achieve - If you want to keep the README slim: then yes you should probably not add it.
But for my use case I just quickly copied the examples over. Because it was a quick start I assumed it should just automatically work. Which it didn't and I got a bit annoyed. That is why I proposed the change. But I leave it up to you to do the merge or not :)

Regarding the `enableLegacyTemplate` bug: I did not know that (I thought only for Angular 4.0.1? Or did you mean 4.0.1+ from the README?)... But I think the bug is not a reason why we should not include a reference to include the configuration -> If people do not add it they see unexpected behavior in the app as soon as the bug is resolved. So I think that would not really be a reason for not including it.
But we should probably open up an issue "test `enableLegacyTemplate`" and test it as soon as the bug is resolved? Depends on if the angular bug is only for 4.0.1 or 4.0.1+

AppModule - agreed :)

**Comment by hotforfeature** [comment]
That section is in the long installation guide. It may make more sense to include a `main.ts` sample in the quick start section that includes everything so devs can copy.

`enableLegacyTemplate` has been broken for a while now, and it affects all versions of Angular 4. I should modify the readme to be more specific on that issue.

**Comment by hotforfeature** [comment]
Going to close this, I added a `main.ts` sample in the quick start section that developers can copy.

**Pull request closed without merging**
