### PR TITLE
Update production-build.md

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
Added description how to generate a PWA

### CODE REVIEW

**Comment by BorntraegerMarc** [comment]
First part for https://github.com/hotforfeature/origami/issues/25 but still work in progress

researching better methods to generate the `ng-manifest.json`

**Comment by hotforfeature** [comment]
Sorry for the delay in getting to this. I think PWA is complex enough to warrant its own document that could be linked to from the production build. Not everyone is creating a PWA, and it's not a simple one-step process to lump in with the build docs.

I'm also not so sure this is the best way to go about handling caching bower_components files. What if we ignored everything from bower_components by default?

For bundled builds, we'd miss out on caching some JS files and unbundled builds would miss a lot of caching potential. Still, I think that's a better starting point. We can add a custom service worker that works in tandem with the ngsw to cache Polymer resources specifically. I'm also wondering if we can use the Polymer CLI-generated service worker and config to fill this role.

Some food for thought and experimentation.

**Comment by BorntraegerMarc** [comment]
> Sorry for the delay in getting to this. I think PWA is complex enough to warrant its own document that could be linked to from the production build. Not everyone is creating a PWA, and it's not a simple one-step process to lump in with the build docs.

Agreed. Probably the better approach

> I'm also not so sure this is the best way to go about handling caching bower_components files. What if we ignored everything from bower_components by default?

I don't think this is the right approach to take. However I know that the current process is far from ideal. But at least we have the caching and the app has the potential to work offline. But the build process definitely needs to change. I suggest we wait to merge this PR until the better process is implemented. So other devs have the current process as a guideline how it *could* be done...

> For bundled builds, we'd miss out on caching some JS files and unbundled builds would miss a lot of caching potential. Still, I think that's a better starting point. We can add a custom service worker that works in tandem with the ngsw to cache Polymer resources specifically. I'm also wondering if we can use the Polymer CLI-generated service worker and config to fill this role.

There seems to be a new method on how to actually generate the manifest: https://github.com/angular/mobile-toolkit/tree/master/service-worker/worker#new-manifest maybe we could use this method instead (combined with the polymer build) so we don't have to manually re-write the manifest. I'll look into it.

**Comment by hotforfeature** [comment]
Going to close this PR as the production build docs with service worker manifest generation will be included in v2

**Pull request closed without merging**
