### PR TITLE
fix(patch): update patch-cli for Angular CLI 6.x

### PR DESCRIPTION
**Pull request by jaichandra**

### CODE REVIEW

**Comment by hotforfeature** [comment]
Thanks for the PR @jaichandra! To maintain backwards compatibility, what if you first check if the new `@angular-devkit` files exist first?

```js
let commonPath = path.resolve(
  __dirname,
  '../../@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js'
);

const isNg6 = path.existsSync(commonPath);
if (!isNg6) {
  commonPath = path.resolve(
    __dirname,
    '../../@angular/cli/models/webpack-configs/common.js'
  );
}
```

Later, depending on what needs to be modified for Angular 5 vs 6, you can use the same boolean.

```js
data = data.replace(
    isNg6 ? /(nodeModules =.*;)/ : /(appRoot =.*;)/,
    `$1
    /* origami patch start */
    const bowerDirs = [
      path.resolve(${isNg6 ? 'root' : 'appRoot'}, 'bower_components'),
      path.resolve(projectRoot, 'bower_components')
    ];

    try {
      const bowerrc = JSON.parse(require('fs').readFileSync(path.resolve(projectRoot, './.bowerrc')));
      if (bowerrc && bowerrc.directory) {
        bowerDirs.push(path.resolve(projectRoot, bowerrc.directory));
      }
    } catch (e) {
      // .bowerrc not present
    }
    /* origami patch end */
  `
  );
```

**Comment by jaichandra** [comment]
looks like `path.existsSync` has to be replaced with `fs.existsSync`

**Comment by hotforfeature** [comment]
@jaichandra that's correct, I also added a couple comments to the review for you to look at.

**Comment by hotforfeature** [comment]
Still need to do a bit more testing before releasing, but I think this is good enough to merge in for now.

**Pull request merged**
